AMBARI-27: Backport Issues from Main trunk

diff --git a/ambari-agent/conf/unix/ambari-agent b/ambari-agent/conf/unix/ambari-agent
--- a/ambari-agent/conf/unix/ambari-agent
+++ b/ambari-agent/conf/unix/ambari-agent
@@ -44,7 +44,11 @@ export CONFIG_FILE="$HOME_DIR/etc/ambari-agent/conf/ambari-agent.ini"
 
 get_agent_property() {
   property_name="$1"
+<<<<<<< HEAD
   value=$(awk -F "=" "/^${property_name}/ {print \$2}" ${CONFIG_FILE})
+=======
+  value=$(awk -F "=" "/^$property_name/ {print \$2}" $CONFIG_FILE)
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
   echo $value
 }
 
@@ -55,12 +59,20 @@ valid_path() {
     echo "path $1 not valid" 1>&2
     exit 1
   fi
+<<<<<<< HEAD
   echo ${value}
+=======
+  echo $value
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 }
 
 
 export PATH=/usr/sbin:/sbin:/usr/lib/ambari-server/*:$PATH
+<<<<<<< HEAD
 export AMBARI_CONF_DIR=${HOME_DIR}/etc/ambari-server/conf:$PATH
+=======
+export AMBARI_CONF_DIR=$HOME_DIR/etc/ambari-server/conf:$PATH
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 
 # Because Ambari rpm unpacks modules here on all systems
 export PYTHONPATH=/usr/lib/ambari-agent/lib:${PYTHONPATH:-}
@@ -77,9 +89,15 @@ KEYSDIR="${KEYSDIR:?}"
 
 AMBARI_AGENT=ambari-agent
 PYTHON_WRAP=/usr/bin/ambari-python-wrap
+<<<<<<< HEAD
 PIDFILE=${AMBARI_PID_DIR}/${AMBARI_AGENT}.pid
 OUTFILE=${AMBARI_AGENT_LOG_DIR}/ambari-agent.out
 LOGFILE=${AMBARI_AGENT_LOG_DIR}/ambari-agent.log
+=======
+PIDFILE=$AMBARI_PID_DIR/$AMBARI_AGENT.pid
+OUTFILE=$AMBARI_AGENT_LOG_DIR/ambari-agent.out
+LOGFILE=$AMBARI_AGENT_LOG_DIR/ambari-agent.log
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 AGENT_SCRIPT=/usr/lib/ambari-agent/lib/ambari_agent/main.py
 AGENT_TMP_DIR=/var/lib/ambari-agent/tmp
 AGENT_WORKING_DIR=/var/lib/ambari-agent
@@ -101,6 +119,7 @@ if [ "$EUID" -ne 0 ] ; then
 fi
 
 # set reliable cwd for this and child processes.
+<<<<<<< HEAD
 cd ${AGENT_WORKING_DIR}
 
 
@@ -133,16 +152,40 @@ change_files_permissions() {
   ambari-sudo.sh chown -R ${current_user} "/var/lib/ambari-agent/cache/"
   ambari-sudo.sh chown 	${current_user} "/usr/lib/ambari-agent/"
   ambari-sudo.sh chown  ${current_user} "/var/lib/ambari-agent/cred"
+=======
+cd $AGENT_WORKING_DIR
+
+change_files_permissions() {
+    if [ ! -z "$KEYSDIR" ]; then
+        ambari-sudo.sh chown -R $current_user "$KEYSDIR"
+    fi
+	ambari-sudo.sh mkdir -p "${AMBARI_PID_DIR:?}"
+	ambari-sudo.sh chown -R $current_user "${AMBARI_PID_DIR:?}/"
+	ambari-sudo.sh mkdir -p "${AMBARI_AGENT_LOG_DIR:?}"
+	ambari-sudo.sh chown -R $current_user:$current_group "${AMBARI_AGENT_LOG_DIR:?}/"
+	ambari-sudo.sh chown -R $current_user "/var/lib/ambari-agent/data/"
+	ambari-sudo.sh chown -R $current_user "/var/lib/ambari-agent/cache/"
+	ambari-sudo.sh chown 	$current_user "/usr/lib/ambari-agent/"
+	ambari-sudo.sh chown  $current_user "/var/lib/ambari-agent/cred"
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 }
 
 
 if [ -z "${PYTHON:-}" ] ; then
+<<<<<<< HEAD
   export PYTHON=`readlink ${PYTHON_WRAP}`
+=======
+  export PYTHON=`readlink $PYTHON_WRAP`
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 fi
 
 # Trying to read the passphrase from an environment
 if [ ! -z ${AMBARI_PASSPHRASE:-} ]; then
+<<<<<<< HEAD
   RESOLVED_AMBARI_PASSPHRASE=${AMBARI_PASSPHRASE}
+=======
+  RESOLVED_AMBARI_PASSPHRASE=$AMBARI_PASSPHRASE
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 fi
 
 # Reading the environment file
@@ -151,8 +194,13 @@ if [ -a /var/lib/ambari-agent/ambari-env.sh ]; then
   . /var/lib/ambari-agent/ambari-env.sh
 fi
 
+<<<<<<< HEAD
 if [ ! -z ${AMBARI_AGENT_LOG_DIR} ]; then
   LOGFILE=${AMBARI_AGENT_LOG_DIR}/ambari-agent.log
+=======
+if [ ! -z $AMBARI_AGENT_LOG_DIR ]; then
+  LOGFILE=$AMBARI_AGENT_LOG_DIR/ambari-agent.log
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 fi
 
 if [ ! -z ${AMBARI_AGENT_OUT_DIR:-} ]; then
@@ -167,6 +215,7 @@ elif [ -z ${RESOLVED_AMBARI_PASSPHRASE:-} ]; then
   RESOLVED_AMBARI_PASSPHRASE="DEV"
 fi
 
+<<<<<<< HEAD
 export AMBARI_PASSPHRASE=${RESOLVED_AMBARI_PASSPHRASE}
 
 
@@ -190,12 +239,32 @@ check_python_version ()
   fi
   echo "Using python " ${PYTHON}
   return ${OK}
+=======
+export AMBARI_PASSPHRASE=$RESOLVED_AMBARI_PASSPHRASE
+
+#echo $AMBARI_PASSPHRASE
+
+# check for version
+check_python_version ()
+{
+  echo "Verifying Python version compatibility..."
+  majversion=`$PYTHON -V 2>&1 | awk '{print $2}' | cut -d'.' -f1`
+  minversion=`$PYTHON -V 2>&1 | awk '{print $2}' | cut -d'.' -f2`
+  numversion=$(( 10 * $majversion + $minversion))
+  if (( $numversion < 26 )); then
+    echo "ERROR: Found Python version $majversion.$minversion. Ambari Agent requires Python version > 2.6"
+    return $NOTOK
+  fi
+  echo "Using python " $PYTHON
+  return $OK
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 }
 
 check_ambari_common_dir ()
 {
   echo "Checking ambari-common dir..."
   # recursively compare all files except 'pyc' and 'pyo' in agent common dir and actual common dir to ensure they are up to date
+<<<<<<< HEAD
   diff -r ${COMMON_DIR} ${COMMON_DIR_AGENT} -x '*.py?'
   OUT=$?
   if [ ${OUT} -ne 0 ];then
@@ -203,6 +272,15 @@ check_ambari_common_dir ()
     return ${NOTOK}
   fi
   return ${OK}
+=======
+  diff -r $COMMON_DIR $COMMON_DIR_AGENT -x '*.py?'
+  OUT=$?
+  if [ $OUT -ne 0 ];then
+    echo "ERROR: ambari_commons folder mismatch. $COMMON_DIR content should be the same as $COMMON_DIR_AGENT. Either ambari-agent is co-hosted with ambari-server and agent was upgraded without server or the link was broken."
+    return $NOTOK
+  fi
+  return $OK
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 }
 
 retcode=0
@@ -210,6 +288,7 @@ retcode=0
 case "${1:-}" in
   start)
         check_python_version
+<<<<<<< HEAD
         if [ "$?" -eq "${NOTOK}" ]; then
           exit -1
         fi
@@ -221,6 +300,21 @@ case "${1:-}" in
             ambari-sudo.sh rm -f ${PIDFILE}
           else
             print_error_bold "$AMBARI_AGENT already running"
+=======
+        if [ "$?" -eq "$NOTOK" ]; then
+          exit -1
+        fi
+        echo "Checking for previously running Ambari Agent..."
+        if [ -f $PIDFILE ]; then
+          PID=`ambari-sudo.sh cat $PIDFILE`
+          if ! (ps -p $PID >/dev/null 2>/dev/null); then
+            echo "$PIDFILE found with no process. Removing $PID..."
+            ambari-sudo.sh rm -f $PIDFILE
+          else
+            tput bold
+            echo "ERROR: $AMBARI_AGENT already running"
+            tput sgr0
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
             echo "Check $PIDFILE for PID."
             exit -1
           fi
@@ -235,15 +329,24 @@ case "${1:-}" in
         echo "Starting ambari-agent"
 
         if [ "${AMBARI_AGENT_RUN_IN_FOREGROUND:-}" == true ] ; then
+<<<<<<< HEAD
           ${PYTHON} ${AMBARI_AGENT_PY_SCRIPT} "$@" > ${OUTFILE} 2>&1
           exit $?
         fi
 
         nohup ${PYTHON} ${AMBARI_AGENT_PY_SCRIPT} "$@" > ${OUTFILE} 2>&1 &
+=======
+          $PYTHON $AMBARI_AGENT_PY_SCRIPT "$@" > $OUTFILE 2>&1
+          exit $?
+        fi
+
+        nohup $PYTHON $AMBARI_AGENT_PY_SCRIPT "$@" > $OUTFILE 2>&1 &
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
 
         sleep 2
         PID=$!
         echo "Verifying $AMBARI_AGENT process status..."
+<<<<<<< HEAD
         if ! (ps -p ${PID} >/dev/null 2>/dev/null); then
           if [ -s ${OUTFILE} ]; then
             print_error "${AMBARI_AGENT} start failed. For more details, see ${OUTFILE}:"
@@ -281,11 +384,53 @@ case "${1:-}" in
           fi
         else
           print_bold "${AMBARI_AGENT} currently not running"
+=======
+        if ! (ps -p $PID >/dev/null 2>/dev/null); then
+          if [ -s $OUTFILE ]; then
+            echo "ERROR: $AMBARI_AGENT start failed. For more details, see $OUTFILE:"
+            echo "===================="
+            tail -n 10 $OUTFILE
+            echo "===================="
+          else
+            echo "ERROR: $AMBARI_AGENT start failed"
+          fi
+          echo "Agent out at: $OUTFILE"
+          echo "Agent log at: $LOGFILE"
+          exit -1
+        fi
+        tput bold
+        echo "Ambari Agent successfully started"
+        tput sgr0
+        echo "Agent PID at: $PIDFILE"
+        echo "Agent out at: $OUTFILE"
+        echo "Agent log at: $LOGFILE"
+        ;;
+  status)
+        if [ -f $PIDFILE ]; then
+          PID=`ambari-sudo.sh cat $PIDFILE`
+          echo "Found $AMBARI_AGENT PID: $PID"
+          if ! (ps -p $PID >/dev/null 2>/dev/null); then
+            echo "$AMBARI_AGENT not running. Stale PID File at: $PIDFILE"
+            retcode=2
+          else
+            tput bold
+            echo "$AMBARI_AGENT running."
+            tput sgr0
+            echo "Agent PID at: $PIDFILE"
+            echo "Agent out at: $OUTFILE"
+            echo "Agent log at: $LOGFILE"
+          fi
+        else
+          tput bold
+          echo "$AMBARI_AGENT currently not running"
+          tput sgr0
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
           retcode=3
         fi
         ;;
   stop)
         check_python_version
+<<<<<<< HEAD
         if [ "$?" -eq "${NOTOK}" ]; then
           exit -1
         fi
@@ -310,13 +455,52 @@ case "${1:-}" in
           print_bold "${AMBARI_AGENT} successfully stopped"
         else
           print_bold "${AMBARI_AGENT} is not running. No PID found at ${PIDFILE}"
+=======
+        if [ "$?" -eq "$NOTOK" ]; then
+          exit -1
+        fi
+        if [ -f $PIDFILE ]; then
+          PID=`ambari-sudo.sh cat $PIDFILE`
+          echo "Found $AMBARI_AGENT PID: $PID"
+          if ! (ps -p $PID >/dev/null 2>/dev/null); then
+            tput bold
+            echo "ERROR: $AMBARI_AGENT not running. Stale PID File at: $PIDFILE"
+            tput sgr0
+          else
+            echo "Stopping $AMBARI_AGENT"
+            change_files_permissions
+            $PYTHON $AGENT_SCRIPT stop
+
+            status ambari-agent 2>/dev/null | grep start 1>/dev/null
+            if [ "$?" -eq 0 ] ; then
+              echo "Stopping $AMBARI_AGENT upstart job"
+              stop ambari-agent > /dev/null
+            fi
+          fi
+          echo "Removing PID file at $PIDFILE"
+          ambari-sudo.sh rm -f $PIDFILE
+          tput bold
+          echo "$AMBARI_AGENT successfully stopped"
+          tput sgr0
+        else
+          tput bold
+          echo "$AMBARI_AGENT is not running. No PID found at $PIDFILE"
+          tput sgr0
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
         fi
         ;;
   restart)
         echo -e "Restarting $AMBARI_AGENT"
+<<<<<<< HEAD
         ${_SCRIPT} stop
         shift
         ${_SCRIPT} start "$@"
+=======
+        scriptpath=$0
+        $scriptpath stop
+        shift
+        $scriptpath start "$@"
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
         retcode=$?
         ;;
   reset)
@@ -324,6 +508,7 @@ case "${1:-}" in
             echo "You must supply the hostname of the Ambari Server with the restore option. (e.g. ambari-agent reset c6401.ambari.apache.org)"
             exit 1
           fi
+<<<<<<< HEAD
           if [ -f ${PIDFILE} ]; then
             echo "${AMBARI_AGENT} is running. You must stop it before using reset."
             exit 1
@@ -337,12 +522,41 @@ case "${1:-}" in
             print_bold "${AMBARI_AGENT} has been reset successfully. Changed Ambari Server hostname to $2 and certificates were cleared."
           else
             print_bold "${AMBARI_AGENT} could not be reset."
+=======
+          if [ -f $PIDFILE ]; then
+            echo "$AMBARI_AGENT is running. You must stop it before using reset."
+            exit 1
+          fi
+          echo -e "Resetting $AMBARI_AGENT"
+          change_files_permissions
+          $PYTHON $AGENT_SCRIPT reset $2
+          retcode=$?
+
+          if [ $retcode -eq 0 ]; then
+            tput bold
+            echo "$AMBARI_AGENT has been reset successfully. Changed Ambari Server hostname to $2 and certificates were cleared."
+            tput sgr0
+          else
+            tput bold
+            echo "$AMBARI_AGENT could not be reset."
+            tput sgr0
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
           fi
           ;;
 
   *)
+<<<<<<< HEAD
         print_bold "Usage: ${_SCRIPT} {start|stop|restart|status|reset <server_hostname>}"
         retcode=1
 esac
 
 exit ${retcode}
+=======
+        tput bold
+        echo "Usage: /usr/sbin/ambari-agent {start|stop|restart|status|reset <server_hostname>}"
+        tput sgr0
+        retcode=1
+esac
+
+exit $retcode
+>>>>>>> bedce4027a (Initial commit based on 2.7.5 release)
